// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type DinoRoute struct {
	ID                  uuid.UUID
	TunnelName          string
	Hostname            string
	DestinationProtocol string
	DestinationIp       string
	DestinationPort     int32
	IsActive            bool
	CreatedAt           pgtype.Timestamp
	UpdatedAt           pgtype.Timestamp
}

type DinoTunnel struct {
	ID         uuid.UUID
	Identifier string
	TokenHash  string
	IsActive   bool
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}
