// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tunnels.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTunnel = `-- name: DeleteTunnel :execresult
DELETE FROM dino.tunnels WHERE identifier = $1
`

func (q *Queries) DeleteTunnel(ctx context.Context, identifier string) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteTunnel, identifier)
}

const insertTunnel = `-- name: InsertTunnel :one
INSERT INTO dino.tunnels (
    identifier,
    token_hash
) VALUES (
    $1, $2
) RETURNING id, identifier, token_hash, is_active, created_at, updated_at
`

type InsertTunnelParams struct {
	Identifier string
	TokenHash  string
}

func (q *Queries) InsertTunnel(ctx context.Context, arg InsertTunnelParams) (DinoTunnel, error) {
	row := q.db.QueryRow(ctx, insertTunnel, arg.Identifier, arg.TokenHash)
	var i DinoTunnel
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTunnels = `-- name: ListTunnels :many
SELECT
    id,
    identifier,
    created_at
FROM
    dino.tunnels
ORDER BY (id, created_at)
LIMIT $1 OFFSET $2
`

type ListTunnelsParams struct {
	Limit  int32
	Offset int32
}

type ListTunnelsRow struct {
	ID         uuid.UUID
	Identifier string
	CreatedAt  pgtype.Timestamp
}

func (q *Queries) ListTunnels(ctx context.Context, arg ListTunnelsParams) ([]ListTunnelsRow, error) {
	rows, err := q.db.Query(ctx, listTunnels, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTunnelsRow{}
	for rows.Next() {
		var i ListTunnelsRow
		if err := rows.Scan(&i.ID, &i.Identifier, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectTunnel = `-- name: SelectTunnel :one
SELECT
    id, identifier, token_hash, is_active, created_at, updated_at
FROM
    dino.tunnels
WHERE
    identifier = $1
`

func (q *Queries) SelectTunnel(ctx context.Context, identifier string) (DinoTunnel, error) {
	row := q.db.QueryRow(ctx, selectTunnel, identifier)
	var i DinoTunnel
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectTunnelToken = `-- name: SelectTunnelToken :one
SELECT
    token_hash
FROM
    dino.tunnels
WHERE
    id = $1
`

func (q *Queries) SelectTunnelToken(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, selectTunnelToken, id)
	var token_hash string
	err := row.Scan(&token_hash)
	return token_hash, err
}

const updateTunnel = `-- name: UpdateTunnel :one
UPDATE dino.tunnels
SET
    identifier = $2
WHERE 
    identifier = $1
RETURNING id, identifier, token_hash, is_active, created_at, updated_at
`

type UpdateTunnelParams struct {
	Identifier   string
	Identifier_2 string
}

func (q *Queries) UpdateTunnel(ctx context.Context, arg UpdateTunnelParams) (DinoTunnel, error) {
	row := q.db.QueryRow(ctx, updateTunnel, arg.Identifier, arg.Identifier_2)
	var i DinoTunnel
	err := row.Scan(
		&i.ID,
		&i.Identifier,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
