// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pb/tunnels/v1/tunnel_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tunnel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tunnel) Reset() {
	*x = Tunnel{}
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tunnel) ProtoMessage() {}

func (x *Tunnel) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tunnel.ProtoReflect.Descriptor instead.
func (*Tunnel) Descriptor() ([]byte, []int) {
	return file_pb_tunnels_v1_tunnel_service_proto_rawDescGZIP(), []int{0}
}

func (x *Tunnel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tunnel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tunnel) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Tunnel) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type TunnelPartial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelPartial) Reset() {
	*x = TunnelPartial{}
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelPartial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelPartial) ProtoMessage() {}

func (x *TunnelPartial) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelPartial.ProtoReflect.Descriptor instead.
func (*TunnelPartial) Descriptor() ([]byte, []int) {
	return file_pb_tunnels_v1_tunnel_service_proto_rawDescGZIP(), []int{1}
}

func (x *TunnelPartial) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TunnelUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldName       string                 `protobuf:"bytes,1,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelUpdate) Reset() {
	*x = TunnelUpdate{}
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelUpdate) ProtoMessage() {}

func (x *TunnelUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelUpdate.ProtoReflect.Descriptor instead.
func (*TunnelUpdate) Descriptor() ([]byte, []int) {
	return file_pb_tunnels_v1_tunnel_service_proto_rawDescGZIP(), []int{2}
}

func (x *TunnelUpdate) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *TunnelUpdate) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type CreateTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelName    string                 `protobuf:"bytes,1,opt,name=tunnel_name,json=tunnelName,proto3" json:"tunnel_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTunnelRequest) Reset() {
	*x = CreateTunnelRequest{}
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTunnelRequest) ProtoMessage() {}

func (x *CreateTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTunnelRequest.ProtoReflect.Descriptor instead.
func (*CreateTunnelRequest) Descriptor() ([]byte, []int) {
	return file_pb_tunnels_v1_tunnel_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTunnelRequest) GetTunnelName() string {
	if x != nil {
		return x.TunnelName
	}
	return ""
}

type CreateTunnelResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Tunnel *Tunnel                `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	// Types that are valid to be assigned to AuthDetails:
	//
	//	*CreateTunnelResponse_SecretKey
	AuthDetails   isCreateTunnelResponse_AuthDetails `protobuf_oneof:"auth_details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTunnelResponse) Reset() {
	*x = CreateTunnelResponse{}
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTunnelResponse) ProtoMessage() {}

func (x *CreateTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTunnelResponse.ProtoReflect.Descriptor instead.
func (*CreateTunnelResponse) Descriptor() ([]byte, []int) {
	return file_pb_tunnels_v1_tunnel_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTunnelResponse) GetTunnel() *Tunnel {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

func (x *CreateTunnelResponse) GetAuthDetails() isCreateTunnelResponse_AuthDetails {
	if x != nil {
		return x.AuthDetails
	}
	return nil
}

func (x *CreateTunnelResponse) GetSecretKey() string {
	if x != nil {
		if x, ok := x.AuthDetails.(*CreateTunnelResponse_SecretKey); ok {
			return x.SecretKey
		}
	}
	return ""
}

type isCreateTunnelResponse_AuthDetails interface {
	isCreateTunnelResponse_AuthDetails()
}

type CreateTunnelResponse_SecretKey struct {
	SecretKey string `protobuf:"bytes,2,opt,name=secret_key,json=secretKey,proto3,oneof"`
}

func (*CreateTunnelResponse_SecretKey) isCreateTunnelResponse_AuthDetails() {}

type GetTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelRequest) Reset() {
	*x = GetTunnelRequest{}
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelRequest) ProtoMessage() {}

func (x *GetTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelRequest.ProtoReflect.Descriptor instead.
func (*GetTunnelRequest) Descriptor() ([]byte, []int) {
	return file_pb_tunnels_v1_tunnel_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetTunnelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnel        *Tunnel                `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTunnelResponse) Reset() {
	*x = GetTunnelResponse{}
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTunnelResponse) ProtoMessage() {}

func (x *GetTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTunnelResponse.ProtoReflect.Descriptor instead.
func (*GetTunnelResponse) Descriptor() ([]byte, []int) {
	return file_pb_tunnels_v1_tunnel_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetTunnelResponse) GetTunnel() *Tunnel {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

type ListTunnelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	ToComplete    bool                   `protobuf:"varint,3,opt,name=to_complete,json=toComplete,proto3" json:"to_complete,omitempty"`
	Complete      string                 `protobuf:"bytes,4,opt,name=complete,proto3" json:"complete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsRequest) Reset() {
	*x = ListTunnelsRequest{}
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsRequest) ProtoMessage() {}

func (x *ListTunnelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsRequest.ProtoReflect.Descriptor instead.
func (*ListTunnelsRequest) Descriptor() ([]byte, []int) {
	return file_pb_tunnels_v1_tunnel_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListTunnelsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTunnelsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTunnelsRequest) GetToComplete() bool {
	if x != nil {
		return x.ToComplete
	}
	return false
}

func (x *ListTunnelsRequest) GetComplete() string {
	if x != nil {
		return x.Complete
	}
	return ""
}

type ListTunnelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnels       []*TunnelPartial       `protobuf:"bytes,1,rep,name=tunnels,proto3" json:"tunnels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTunnelsResponse) Reset() {
	*x = ListTunnelsResponse{}
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTunnelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTunnelsResponse) ProtoMessage() {}

func (x *ListTunnelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTunnelsResponse.ProtoReflect.Descriptor instead.
func (*ListTunnelsResponse) Descriptor() ([]byte, []int) {
	return file_pb_tunnels_v1_tunnel_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListTunnelsResponse) GetTunnels() []*TunnelPartial {
	if x != nil {
		return x.Tunnels
	}
	return nil
}

type UpdateTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelUpdate  *TunnelUpdate          `protobuf:"bytes,1,opt,name=tunnel_update,json=tunnelUpdate,proto3" json:"tunnel_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTunnelRequest) Reset() {
	*x = UpdateTunnelRequest{}
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTunnelRequest) ProtoMessage() {}

func (x *UpdateTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTunnelRequest.ProtoReflect.Descriptor instead.
func (*UpdateTunnelRequest) Descriptor() ([]byte, []int) {
	return file_pb_tunnels_v1_tunnel_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTunnelRequest) GetTunnelUpdate() *TunnelUpdate {
	if x != nil {
		return x.TunnelUpdate
	}
	return nil
}

type UpdateTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnel        *Tunnel                `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTunnelResponse) Reset() {
	*x = UpdateTunnelResponse{}
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTunnelResponse) ProtoMessage() {}

func (x *UpdateTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTunnelResponse.ProtoReflect.Descriptor instead.
func (*UpdateTunnelResponse) Descriptor() ([]byte, []int) {
	return file_pb_tunnels_v1_tunnel_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateTunnelResponse) GetTunnel() *Tunnel {
	if x != nil {
		return x.Tunnel
	}
	return nil
}

type DeleteTunnelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTunnelRequest) Reset() {
	*x = DeleteTunnelRequest{}
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTunnelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTunnelRequest) ProtoMessage() {}

func (x *DeleteTunnelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTunnelRequest.ProtoReflect.Descriptor instead.
func (*DeleteTunnelRequest) Descriptor() ([]byte, []int) {
	return file_pb_tunnels_v1_tunnel_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteTunnelRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteTunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTunnelResponse) Reset() {
	*x = DeleteTunnelResponse{}
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTunnelResponse) ProtoMessage() {}

func (x *DeleteTunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_tunnels_v1_tunnel_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTunnelResponse.ProtoReflect.Descriptor instead.
func (*DeleteTunnelResponse) Descriptor() ([]byte, []int) {
	return file_pb_tunnels_v1_tunnel_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTunnelResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

var File_pb_tunnels_v1_tunnel_service_proto protoreflect.FileDescriptor

const file_pb_tunnels_v1_tunnel_service_proto_rawDesc = "" +
	"\n" +
	"\"pb/tunnels/v1/tunnel_service.proto\x12\ttunnel.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x01\n" +
	"\x06Tunnel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"#\n" +
	"\rTunnelPartial\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"D\n" +
	"\fTunnelUpdate\x12\x19\n" +
	"\bold_name\x18\x01 \x01(\tR\aoldName\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"6\n" +
	"\x13CreateTunnelRequest\x12\x1f\n" +
	"\vtunnel_name\x18\x01 \x01(\tR\n" +
	"tunnelName\"r\n" +
	"\x14CreateTunnelResponse\x12)\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x11.tunnel.v1.TunnelR\x06tunnel\x12\x1f\n" +
	"\n" +
	"secret_key\x18\x02 \x01(\tH\x00R\tsecretKeyB\x0e\n" +
	"\fauth_details\"&\n" +
	"\x10GetTunnelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\">\n" +
	"\x11GetTunnelResponse\x12)\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x11.tunnel.v1.TunnelR\x06tunnel\"\x7f\n" +
	"\x12ListTunnelsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x1f\n" +
	"\vto_complete\x18\x03 \x01(\bR\n" +
	"toComplete\x12\x1a\n" +
	"\bcomplete\x18\x04 \x01(\tR\bcomplete\"I\n" +
	"\x13ListTunnelsResponse\x122\n" +
	"\atunnels\x18\x01 \x03(\v2\x18.tunnel.v1.TunnelPartialR\atunnels\"S\n" +
	"\x13UpdateTunnelRequest\x12<\n" +
	"\rtunnel_update\x18\x01 \x01(\v2\x17.tunnel.v1.TunnelUpdateR\ftunnelUpdate\"A\n" +
	"\x14UpdateTunnelResponse\x12)\n" +
	"\x06tunnel\x18\x01 \x01(\v2\x11.tunnel.v1.TunnelR\x06tunnel\")\n" +
	"\x13DeleteTunnelRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"D\n" +
	"\x14DeleteTunnelResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty2\xa2\x03\n" +
	"\rTunnelService\x12Q\n" +
	"\fCreateTunnel\x12\x1e.tunnel.v1.CreateTunnelRequest\x1a\x1f.tunnel.v1.CreateTunnelResponse\"\x00\x12H\n" +
	"\tGetTunnel\x12\x1b.tunnel.v1.GetTunnelRequest\x1a\x1c.tunnel.v1.GetTunnelResponse\"\x00\x12N\n" +
	"\vListTunnels\x12\x1d.tunnel.v1.ListTunnelsRequest\x1a\x1e.tunnel.v1.ListTunnelsResponse\"\x00\x12Q\n" +
	"\fUpdateTunnel\x12\x1e.tunnel.v1.UpdateTunnelRequest\x1a\x1f.tunnel.v1.UpdateTunnelResponse\"\x00\x12Q\n" +
	"\fDeleteTunnel\x12\x1e.tunnel.v1.DeleteTunnelRequest\x1a\x1f.tunnel.v1.DeleteTunnelResponse\"\x00B'Z%soft.structx.io/dino/protos/tunnel/v1b\x06proto3"

var (
	file_pb_tunnels_v1_tunnel_service_proto_rawDescOnce sync.Once
	file_pb_tunnels_v1_tunnel_service_proto_rawDescData []byte
)

func file_pb_tunnels_v1_tunnel_service_proto_rawDescGZIP() []byte {
	file_pb_tunnels_v1_tunnel_service_proto_rawDescOnce.Do(func() {
		file_pb_tunnels_v1_tunnel_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_tunnels_v1_tunnel_service_proto_rawDesc), len(file_pb_tunnels_v1_tunnel_service_proto_rawDesc)))
	})
	return file_pb_tunnels_v1_tunnel_service_proto_rawDescData
}

var file_pb_tunnels_v1_tunnel_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pb_tunnels_v1_tunnel_service_proto_goTypes = []any{
	(*Tunnel)(nil),                // 0: tunnel.v1.Tunnel
	(*TunnelPartial)(nil),         // 1: tunnel.v1.TunnelPartial
	(*TunnelUpdate)(nil),          // 2: tunnel.v1.TunnelUpdate
	(*CreateTunnelRequest)(nil),   // 3: tunnel.v1.CreateTunnelRequest
	(*CreateTunnelResponse)(nil),  // 4: tunnel.v1.CreateTunnelResponse
	(*GetTunnelRequest)(nil),      // 5: tunnel.v1.GetTunnelRequest
	(*GetTunnelResponse)(nil),     // 6: tunnel.v1.GetTunnelResponse
	(*ListTunnelsRequest)(nil),    // 7: tunnel.v1.ListTunnelsRequest
	(*ListTunnelsResponse)(nil),   // 8: tunnel.v1.ListTunnelsResponse
	(*UpdateTunnelRequest)(nil),   // 9: tunnel.v1.UpdateTunnelRequest
	(*UpdateTunnelResponse)(nil),  // 10: tunnel.v1.UpdateTunnelResponse
	(*DeleteTunnelRequest)(nil),   // 11: tunnel.v1.DeleteTunnelRequest
	(*DeleteTunnelResponse)(nil),  // 12: tunnel.v1.DeleteTunnelResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 14: google.protobuf.Empty
}
var file_pb_tunnels_v1_tunnel_service_proto_depIdxs = []int32{
	13, // 0: tunnel.v1.Tunnel.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: tunnel.v1.Tunnel.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: tunnel.v1.CreateTunnelResponse.tunnel:type_name -> tunnel.v1.Tunnel
	0,  // 3: tunnel.v1.GetTunnelResponse.tunnel:type_name -> tunnel.v1.Tunnel
	1,  // 4: tunnel.v1.ListTunnelsResponse.tunnels:type_name -> tunnel.v1.TunnelPartial
	2,  // 5: tunnel.v1.UpdateTunnelRequest.tunnel_update:type_name -> tunnel.v1.TunnelUpdate
	0,  // 6: tunnel.v1.UpdateTunnelResponse.tunnel:type_name -> tunnel.v1.Tunnel
	14, // 7: tunnel.v1.DeleteTunnelResponse.empty:type_name -> google.protobuf.Empty
	3,  // 8: tunnel.v1.TunnelService.CreateTunnel:input_type -> tunnel.v1.CreateTunnelRequest
	5,  // 9: tunnel.v1.TunnelService.GetTunnel:input_type -> tunnel.v1.GetTunnelRequest
	7,  // 10: tunnel.v1.TunnelService.ListTunnels:input_type -> tunnel.v1.ListTunnelsRequest
	9,  // 11: tunnel.v1.TunnelService.UpdateTunnel:input_type -> tunnel.v1.UpdateTunnelRequest
	11, // 12: tunnel.v1.TunnelService.DeleteTunnel:input_type -> tunnel.v1.DeleteTunnelRequest
	4,  // 13: tunnel.v1.TunnelService.CreateTunnel:output_type -> tunnel.v1.CreateTunnelResponse
	6,  // 14: tunnel.v1.TunnelService.GetTunnel:output_type -> tunnel.v1.GetTunnelResponse
	8,  // 15: tunnel.v1.TunnelService.ListTunnels:output_type -> tunnel.v1.ListTunnelsResponse
	10, // 16: tunnel.v1.TunnelService.UpdateTunnel:output_type -> tunnel.v1.UpdateTunnelResponse
	12, // 17: tunnel.v1.TunnelService.DeleteTunnel:output_type -> tunnel.v1.DeleteTunnelResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pb_tunnels_v1_tunnel_service_proto_init() }
func file_pb_tunnels_v1_tunnel_service_proto_init() {
	if File_pb_tunnels_v1_tunnel_service_proto != nil {
		return
	}
	file_pb_tunnels_v1_tunnel_service_proto_msgTypes[4].OneofWrappers = []any{
		(*CreateTunnelResponse_SecretKey)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_tunnels_v1_tunnel_service_proto_rawDesc), len(file_pb_tunnels_v1_tunnel_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_tunnels_v1_tunnel_service_proto_goTypes,
		DependencyIndexes: file_pb_tunnels_v1_tunnel_service_proto_depIdxs,
		MessageInfos:      file_pb_tunnels_v1_tunnel_service_proto_msgTypes,
	}.Build()
	File_pb_tunnels_v1_tunnel_service_proto = out.File
	file_pb_tunnels_v1_tunnel_service_proto_goTypes = nil
	file_pb_tunnels_v1_tunnel_service_proto_depIdxs = nil
}
