// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pb/routes/v1/route_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnel        string                 `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	DestProtocol  string                 `protobuf:"bytes,3,opt,name=dest_protocol,json=destProtocol,proto3" json:"dest_protocol,omitempty"`
	DestAddr      string                 `protobuf:"bytes,4,opt,name=dest_addr,json=destAddr,proto3" json:"dest_addr,omitempty"`
	DestPort      uint32                 `protobuf:"varint,5,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteCreate) Reset() {
	*x = RouteCreate{}
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteCreate) ProtoMessage() {}

func (x *RouteCreate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteCreate.ProtoReflect.Descriptor instead.
func (*RouteCreate) Descriptor() ([]byte, []int) {
	return file_pb_routes_v1_route_service_proto_rawDescGZIP(), []int{0}
}

func (x *RouteCreate) GetTunnel() string {
	if x != nil {
		return x.Tunnel
	}
	return ""
}

func (x *RouteCreate) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RouteCreate) GetDestProtocol() string {
	if x != nil {
		return x.DestProtocol
	}
	return ""
}

func (x *RouteCreate) GetDestAddr() string {
	if x != nil {
		return x.DestAddr
	}
	return ""
}

func (x *RouteCreate) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Tunnel        string                 `protobuf:"bytes,4,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_pb_routes_v1_route_service_proto_rawDescGZIP(), []int{1}
}

func (x *Route) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Route) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Route) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Route) GetTunnel() string {
	if x != nil {
		return x.Tunnel
	}
	return ""
}

func (x *Route) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Route) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RoutePartial struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutePartial) Reset() {
	*x = RoutePartial{}
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePartial) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePartial) ProtoMessage() {}

func (x *RoutePartial) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePartial.ProtoReflect.Descriptor instead.
func (*RoutePartial) Descriptor() ([]byte, []int) {
	return file_pb_routes_v1_route_service_proto_rawDescGZIP(), []int{2}
}

func (x *RoutePartial) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *RoutePartial) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type RouteUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	DestProtocol  string                 `protobuf:"bytes,3,opt,name=dest_protocol,json=destProtocol,proto3" json:"dest_protocol,omitempty"`
	DestAddr      string                 `protobuf:"bytes,4,opt,name=dest_addr,json=destAddr,proto3" json:"dest_addr,omitempty"`
	DestPort      uint32                 `protobuf:"varint,5,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteUpdate) Reset() {
	*x = RouteUpdate{}
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteUpdate) ProtoMessage() {}

func (x *RouteUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteUpdate.ProtoReflect.Descriptor instead.
func (*RouteUpdate) Descriptor() ([]byte, []int) {
	return file_pb_routes_v1_route_service_proto_rawDescGZIP(), []int{3}
}

func (x *RouteUpdate) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *RouteUpdate) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RouteUpdate) GetDestProtocol() string {
	if x != nil {
		return x.DestProtocol
	}
	return ""
}

func (x *RouteUpdate) GetDestAddr() string {
	if x != nil {
		return x.DestAddr
	}
	return ""
}

func (x *RouteUpdate) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

func (x *RouteUpdate) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type CreateRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Create        *RouteCreate           `protobuf:"bytes,1,opt,name=create,proto3" json:"create,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRouteRequest) Reset() {
	*x = CreateRouteRequest{}
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteRequest) ProtoMessage() {}

func (x *CreateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteRequest.ProtoReflect.Descriptor instead.
func (*CreateRouteRequest) Descriptor() ([]byte, []int) {
	return file_pb_routes_v1_route_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRouteRequest) GetCreate() *RouteCreate {
	if x != nil {
		return x.Create
	}
	return nil
}

type CreateRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRouteResponse) Reset() {
	*x = CreateRouteResponse{}
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteResponse) ProtoMessage() {}

func (x *CreateRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteResponse.ProtoReflect.Descriptor instead.
func (*CreateRouteResponse) Descriptor() ([]byte, []int) {
	return file_pb_routes_v1_route_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type GetRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteRequest) Reset() {
	*x = GetRouteRequest{}
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteRequest) ProtoMessage() {}

func (x *GetRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteRequest.ProtoReflect.Descriptor instead.
func (*GetRouteRequest) Descriptor() ([]byte, []int) {
	return file_pb_routes_v1_route_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetRouteRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type GetRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteResponse) Reset() {
	*x = GetRouteResponse{}
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteResponse) ProtoMessage() {}

func (x *GetRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteResponse.ProtoReflect.Descriptor instead.
func (*GetRouteResponse) Descriptor() ([]byte, []int) {
	return file_pb_routes_v1_route_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetRouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type ListRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tunnel        string                 `protobuf:"bytes,1,opt,name=tunnel,proto3" json:"tunnel,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_pb_routes_v1_route_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListRoutesRequest) GetTunnel() string {
	if x != nil {
		return x.Tunnel
	}
	return ""
}

func (x *ListRoutesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRoutesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partials      []*RoutePartial        `protobuf:"bytes,1,rep,name=partials,proto3" json:"partials,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesResponse) Reset() {
	*x = ListRoutesResponse{}
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesResponse) ProtoMessage() {}

func (x *ListRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesResponse.ProtoReflect.Descriptor instead.
func (*ListRoutesResponse) Descriptor() ([]byte, []int) {
	return file_pb_routes_v1_route_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListRoutesResponse) GetPartials() []*RoutePartial {
	if x != nil {
		return x.Partials
	}
	return nil
}

type UpdateRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Update        *RouteUpdate           `protobuf:"bytes,1,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRouteRequest) Reset() {
	*x = UpdateRouteRequest{}
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRouteRequest) ProtoMessage() {}

func (x *UpdateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRouteRequest.ProtoReflect.Descriptor instead.
func (*UpdateRouteRequest) Descriptor() ([]byte, []int) {
	return file_pb_routes_v1_route_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRouteRequest) GetUpdate() *RouteUpdate {
	if x != nil {
		return x.Update
	}
	return nil
}

type UpdateRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRouteResponse) Reset() {
	*x = UpdateRouteResponse{}
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRouteResponse) ProtoMessage() {}

func (x *UpdateRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRouteResponse.ProtoReflect.Descriptor instead.
func (*UpdateRouteResponse) Descriptor() ([]byte, []int) {
	return file_pb_routes_v1_route_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateRouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type DeleteRouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRouteRequest) Reset() {
	*x = DeleteRouteRequest{}
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteRequest) ProtoMessage() {}

func (x *DeleteRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRouteRequest) Descriptor() ([]byte, []int) {
	return file_pb_routes_v1_route_service_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRouteRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type DeleteRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRouteResponse) Reset() {
	*x = DeleteRouteResponse{}
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteResponse) ProtoMessage() {}

func (x *DeleteRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_routes_v1_route_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteResponse.ProtoReflect.Descriptor instead.
func (*DeleteRouteResponse) Descriptor() ([]byte, []int) {
	return file_pb_routes_v1_route_service_proto_rawDescGZIP(), []int{13}
}

var File_pb_routes_v1_route_service_proto protoreflect.FileDescriptor

const file_pb_routes_v1_route_service_proto_rawDesc = "" +
	"\n" +
	" pb/routes/v1/route_service.proto\x12\troutes.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x01\n" +
	"\vRouteCreate\x12\x16\n" +
	"\x06tunnel\x18\x01 \x01(\tR\x06tunnel\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12#\n" +
	"\rdest_protocol\x18\x03 \x01(\tR\fdestProtocol\x12\x1b\n" +
	"\tdest_addr\x18\x04 \x01(\tR\bdestAddr\x12\x1b\n" +
	"\tdest_port\x18\x05 \x01(\rR\bdestPort\"\xd5\x01\n" +
	"\x05Route\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x16\n" +
	"\x06tunnel\x18\x04 \x01(\tR\x06tunnel\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"<\n" +
	"\fRoutePartial\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\"\xb4\x01\n" +
	"\vRouteUpdate\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12#\n" +
	"\rdest_protocol\x18\x03 \x01(\tR\fdestProtocol\x12\x1b\n" +
	"\tdest_addr\x18\x04 \x01(\tR\bdestAddr\x12\x1b\n" +
	"\tdest_port\x18\x05 \x01(\rR\bdestPort\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\"D\n" +
	"\x12CreateRouteRequest\x12.\n" +
	"\x06create\x18\x01 \x01(\v2\x16.routes.v1.RouteCreateR\x06create\"=\n" +
	"\x13CreateRouteResponse\x12&\n" +
	"\x05route\x18\x01 \x01(\v2\x10.routes.v1.RouteR\x05route\"-\n" +
	"\x0fGetRouteRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\":\n" +
	"\x10GetRouteResponse\x12&\n" +
	"\x05route\x18\x01 \x01(\v2\x10.routes.v1.RouteR\x05route\"Y\n" +
	"\x11ListRoutesRequest\x12\x16\n" +
	"\x06tunnel\x18\x01 \x01(\tR\x06tunnel\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"I\n" +
	"\x12ListRoutesResponse\x123\n" +
	"\bpartials\x18\x01 \x03(\v2\x17.routes.v1.RoutePartialR\bpartials\"D\n" +
	"\x12UpdateRouteRequest\x12.\n" +
	"\x06update\x18\x01 \x01(\v2\x16.routes.v1.RouteUpdateR\x06update\"=\n" +
	"\x13UpdateRouteResponse\x12&\n" +
	"\x05route\x18\x01 \x01(\v2\x10.routes.v1.RouteR\x05route\"0\n" +
	"\x12DeleteRouteRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\"\x15\n" +
	"\x13DeleteRouteResponse2\x92\x03\n" +
	"\fRouteService\x12N\n" +
	"\vCreateRoute\x12\x1d.routes.v1.CreateRouteRequest\x1a\x1e.routes.v1.CreateRouteResponse\"\x00\x12E\n" +
	"\bGetRoute\x12\x1a.routes.v1.GetRouteRequest\x1a\x1b.routes.v1.GetRouteResponse\"\x00\x12K\n" +
	"\n" +
	"ListRoutes\x12\x1c.routes.v1.ListRoutesRequest\x1a\x1d.routes.v1.ListRoutesResponse\"\x00\x12N\n" +
	"\vUpdateRoute\x12\x1d.routes.v1.UpdateRouteRequest\x1a\x1e.routes.v1.UpdateRouteResponse\"\x00\x12N\n" +
	"\vDeleteRoute\x12\x1d.routes.v1.DeleteRouteRequest\x1a\x1e.routes.v1.DeleteRouteResponse\"\x00B'Z%soft.structx.io/dino/protos/routes/v1b\x06proto3"

var (
	file_pb_routes_v1_route_service_proto_rawDescOnce sync.Once
	file_pb_routes_v1_route_service_proto_rawDescData []byte
)

func file_pb_routes_v1_route_service_proto_rawDescGZIP() []byte {
	file_pb_routes_v1_route_service_proto_rawDescOnce.Do(func() {
		file_pb_routes_v1_route_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_routes_v1_route_service_proto_rawDesc), len(file_pb_routes_v1_route_service_proto_rawDesc)))
	})
	return file_pb_routes_v1_route_service_proto_rawDescData
}

var file_pb_routes_v1_route_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_pb_routes_v1_route_service_proto_goTypes = []any{
	(*RouteCreate)(nil),           // 0: routes.v1.RouteCreate
	(*Route)(nil),                 // 1: routes.v1.Route
	(*RoutePartial)(nil),          // 2: routes.v1.RoutePartial
	(*RouteUpdate)(nil),           // 3: routes.v1.RouteUpdate
	(*CreateRouteRequest)(nil),    // 4: routes.v1.CreateRouteRequest
	(*CreateRouteResponse)(nil),   // 5: routes.v1.CreateRouteResponse
	(*GetRouteRequest)(nil),       // 6: routes.v1.GetRouteRequest
	(*GetRouteResponse)(nil),      // 7: routes.v1.GetRouteResponse
	(*ListRoutesRequest)(nil),     // 8: routes.v1.ListRoutesRequest
	(*ListRoutesResponse)(nil),    // 9: routes.v1.ListRoutesResponse
	(*UpdateRouteRequest)(nil),    // 10: routes.v1.UpdateRouteRequest
	(*UpdateRouteResponse)(nil),   // 11: routes.v1.UpdateRouteResponse
	(*DeleteRouteRequest)(nil),    // 12: routes.v1.DeleteRouteRequest
	(*DeleteRouteResponse)(nil),   // 13: routes.v1.DeleteRouteResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_pb_routes_v1_route_service_proto_depIdxs = []int32{
	14, // 0: routes.v1.Route.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: routes.v1.Route.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: routes.v1.CreateRouteRequest.create:type_name -> routes.v1.RouteCreate
	1,  // 3: routes.v1.CreateRouteResponse.route:type_name -> routes.v1.Route
	1,  // 4: routes.v1.GetRouteResponse.route:type_name -> routes.v1.Route
	2,  // 5: routes.v1.ListRoutesResponse.partials:type_name -> routes.v1.RoutePartial
	3,  // 6: routes.v1.UpdateRouteRequest.update:type_name -> routes.v1.RouteUpdate
	1,  // 7: routes.v1.UpdateRouteResponse.route:type_name -> routes.v1.Route
	4,  // 8: routes.v1.RouteService.CreateRoute:input_type -> routes.v1.CreateRouteRequest
	6,  // 9: routes.v1.RouteService.GetRoute:input_type -> routes.v1.GetRouteRequest
	8,  // 10: routes.v1.RouteService.ListRoutes:input_type -> routes.v1.ListRoutesRequest
	10, // 11: routes.v1.RouteService.UpdateRoute:input_type -> routes.v1.UpdateRouteRequest
	12, // 12: routes.v1.RouteService.DeleteRoute:input_type -> routes.v1.DeleteRouteRequest
	5,  // 13: routes.v1.RouteService.CreateRoute:output_type -> routes.v1.CreateRouteResponse
	7,  // 14: routes.v1.RouteService.GetRoute:output_type -> routes.v1.GetRouteResponse
	9,  // 15: routes.v1.RouteService.ListRoutes:output_type -> routes.v1.ListRoutesResponse
	11, // 16: routes.v1.RouteService.UpdateRoute:output_type -> routes.v1.UpdateRouteResponse
	13, // 17: routes.v1.RouteService.DeleteRoute:output_type -> routes.v1.DeleteRouteResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pb_routes_v1_route_service_proto_init() }
func file_pb_routes_v1_route_service_proto_init() {
	if File_pb_routes_v1_route_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_routes_v1_route_service_proto_rawDesc), len(file_pb_routes_v1_route_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_routes_v1_route_service_proto_goTypes,
		DependencyIndexes: file_pb_routes_v1_route_service_proto_depIdxs,
		MessageInfos:      file_pb_routes_v1_route_service_proto_msgTypes,
	}.Build()
	File_pb_routes_v1_route_service_proto = out.File
	file_pb_routes_v1_route_service_proto_goTypes = nil
	file_pb_routes_v1_route_service_proto_depIdxs = nil
}
