// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pb/rtunnel/v1/rtunnel_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type REVERSETUNNELPROTOCOL int32

const (
	REVERSETUNNELPROTOCOL_REVERSETUNNELPROTOCOL_UNSPECIFIED REVERSETUNNELPROTOCOL = 0
	REVERSETUNNELPROTOCOL_REVERSETUNNELPROTOCOL_TCP         REVERSETUNNELPROTOCOL = 1
	REVERSETUNNELPROTOCOL_REVERSETUNNELPROTOCOL_UDP         REVERSETUNNELPROTOCOL = 2
	REVERSETUNNELPROTOCOL_REVERSETUNNELPROTOCOL_HTTP        REVERSETUNNELPROTOCOL = 3
	REVERSETUNNELPROTOCOL_REVERSETUNNELPROTOCOL_HTTPS       REVERSETUNNELPROTOCOL = 4
)

// Enum value maps for REVERSETUNNELPROTOCOL.
var (
	REVERSETUNNELPROTOCOL_name = map[int32]string{
		0: "REVERSETUNNELPROTOCOL_UNSPECIFIED",
		1: "REVERSETUNNELPROTOCOL_TCP",
		2: "REVERSETUNNELPROTOCOL_UDP",
		3: "REVERSETUNNELPROTOCOL_HTTP",
		4: "REVERSETUNNELPROTOCOL_HTTPS",
	}
	REVERSETUNNELPROTOCOL_value = map[string]int32{
		"REVERSETUNNELPROTOCOL_UNSPECIFIED": 0,
		"REVERSETUNNELPROTOCOL_TCP":         1,
		"REVERSETUNNELPROTOCOL_UDP":         2,
		"REVERSETUNNELPROTOCOL_HTTP":        3,
		"REVERSETUNNELPROTOCOL_HTTPS":       4,
	}
)

func (x REVERSETUNNELPROTOCOL) Enum() *REVERSETUNNELPROTOCOL {
	p := new(REVERSETUNNELPROTOCOL)
	*p = x
	return p
}

func (x REVERSETUNNELPROTOCOL) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (REVERSETUNNELPROTOCOL) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_rtunnel_v1_rtunnel_service_proto_enumTypes[0].Descriptor()
}

func (REVERSETUNNELPROTOCOL) Type() protoreflect.EnumType {
	return &file_pb_rtunnel_v1_rtunnel_service_proto_enumTypes[0]
}

func (x REVERSETUNNELPROTOCOL) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use REVERSETUNNELPROTOCOL.Descriptor instead.
func (REVERSETUNNELPROTOCOL) EnumDescriptor() ([]byte, []int) {
	return file_pb_rtunnel_v1_rtunnel_service_proto_rawDescGZIP(), []int{0}
}

type TunnelMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TunnelMessage_Data
	//	*TunnelMessage_NewConnection
	//	*TunnelMessage_CloseConnection
	//	*TunnelMessage_RouteUpdates
	Payload       isTunnelMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelMessage) Reset() {
	*x = TunnelMessage{}
	mi := &file_pb_rtunnel_v1_rtunnel_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelMessage) ProtoMessage() {}

func (x *TunnelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rtunnel_v1_rtunnel_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelMessage.ProtoReflect.Descriptor instead.
func (*TunnelMessage) Descriptor() ([]byte, []int) {
	return file_pb_rtunnel_v1_rtunnel_service_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TunnelMessage) GetPayload() isTunnelMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TunnelMessage) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *TunnelMessage) GetNewConnection() *NewConnection {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_NewConnection); ok {
			return x.NewConnection
		}
	}
	return nil
}

func (x *TunnelMessage) GetCloseConnection() *CloseConnection {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_CloseConnection); ok {
			return x.CloseConnection
		}
	}
	return nil
}

func (x *TunnelMessage) GetRouteUpdates() *Route {
	if x != nil {
		if x, ok := x.Payload.(*TunnelMessage_RouteUpdates); ok {
			return x.RouteUpdates
		}
	}
	return nil
}

type isTunnelMessage_Payload interface {
	isTunnelMessage_Payload()
}

type TunnelMessage_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

type TunnelMessage_NewConnection struct {
	NewConnection *NewConnection `protobuf:"bytes,3,opt,name=new_connection,json=newConnection,proto3,oneof"`
}

type TunnelMessage_CloseConnection struct {
	CloseConnection *CloseConnection `protobuf:"bytes,4,opt,name=close_connection,json=closeConnection,proto3,oneof"`
}

type TunnelMessage_RouteUpdates struct {
	RouteUpdates *Route `protobuf:"bytes,5,opt,name=route_updates,json=routeUpdates,proto3,oneof"`
}

func (*TunnelMessage_Data) isTunnelMessage_Payload() {}

func (*TunnelMessage_NewConnection) isTunnelMessage_Payload() {}

func (*TunnelMessage_CloseConnection) isTunnelMessage_Payload() {}

func (*TunnelMessage_RouteUpdates) isTunnelMessage_Payload() {}

type Route struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Hostname            string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	DestinationProtocol string                 `protobuf:"bytes,2,opt,name=destination_protocol,json=destinationProtocol,proto3" json:"destination_protocol,omitempty"`
	DestinationIp       string                 `protobuf:"bytes,3,opt,name=destination_ip,json=destinationIp,proto3" json:"destination_ip,omitempty"`
	DestinationPort     uint32                 `protobuf:"varint,4,opt,name=destination_port,json=destinationPort,proto3" json:"destination_port,omitempty"`
	IsDeleted           bool                   `protobuf:"varint,5,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_pb_rtunnel_v1_rtunnel_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rtunnel_v1_rtunnel_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_pb_rtunnel_v1_rtunnel_service_proto_rawDescGZIP(), []int{1}
}

func (x *Route) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Route) GetDestinationProtocol() string {
	if x != nil {
		return x.DestinationProtocol
	}
	return ""
}

func (x *Route) GetDestinationIp() string {
	if x != nil {
		return x.DestinationIp
	}
	return ""
}

func (x *Route) GetDestinationPort() uint32 {
	if x != nil {
		return x.DestinationPort
	}
	return 0
}

func (x *Route) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type NewConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      REVERSETUNNELPROTOCOL  `protobuf:"varint,1,opt,name=protocol,proto3,enum=rtunnel.v1.REVERSETUNNELPROTOCOL" json:"protocol,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewConnection) Reset() {
	*x = NewConnection{}
	mi := &file_pb_rtunnel_v1_rtunnel_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewConnection) ProtoMessage() {}

func (x *NewConnection) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rtunnel_v1_rtunnel_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewConnection.ProtoReflect.Descriptor instead.
func (*NewConnection) Descriptor() ([]byte, []int) {
	return file_pb_rtunnel_v1_rtunnel_service_proto_rawDescGZIP(), []int{2}
}

func (x *NewConnection) GetProtocol() REVERSETUNNELPROTOCOL {
	if x != nil {
		return x.Protocol
	}
	return REVERSETUNNELPROTOCOL_REVERSETUNNELPROTOCOL_UNSPECIFIED
}

func (x *NewConnection) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type CloseConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseConnection) Reset() {
	*x = CloseConnection{}
	mi := &file_pb_rtunnel_v1_rtunnel_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseConnection) ProtoMessage() {}

func (x *CloseConnection) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rtunnel_v1_rtunnel_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseConnection.ProtoReflect.Descriptor instead.
func (*CloseConnection) Descriptor() ([]byte, []int) {
	return file_pb_rtunnel_v1_rtunnel_service_proto_rawDescGZIP(), []int{3}
}

func (x *CloseConnection) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_pb_rtunnel_v1_rtunnel_service_proto protoreflect.FileDescriptor

const file_pb_rtunnel_v1_rtunnel_service_proto_rawDesc = "" +
	"\n" +
	"#pb/rtunnel/v1/rtunnel_service.proto\x12\n" +
	"rtunnel.v1\"\x97\x02\n" +
	"\rTunnelMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04data\x12B\n" +
	"\x0enew_connection\x18\x03 \x01(\v2\x19.rtunnel.v1.NewConnectionH\x00R\rnewConnection\x12H\n" +
	"\x10close_connection\x18\x04 \x01(\v2\x1b.rtunnel.v1.CloseConnectionH\x00R\x0fcloseConnection\x128\n" +
	"\rroute_updates\x18\x05 \x01(\v2\x11.rtunnel.v1.RouteH\x00R\frouteUpdatesB\t\n" +
	"\apayload\"\xc7\x01\n" +
	"\x05Route\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x121\n" +
	"\x14destination_protocol\x18\x02 \x01(\tR\x13destinationProtocol\x12%\n" +
	"\x0edestination_ip\x18\x03 \x01(\tR\rdestinationIp\x12)\n" +
	"\x10destination_port\x18\x04 \x01(\rR\x0fdestinationPort\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\x05 \x01(\bR\tisDeleted\"p\n" +
	"\rNewConnection\x12=\n" +
	"\bprotocol\x18\x01 \x01(\x0e2!.rtunnel.v1.REVERSETUNNELPROTOCOLR\bprotocol\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\"2\n" +
	"\x0fCloseConnection\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode*\xbd\x01\n" +
	"\x15REVERSETUNNELPROTOCOL\x12%\n" +
	"!REVERSETUNNELPROTOCOL_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19REVERSETUNNELPROTOCOL_TCP\x10\x01\x12\x1d\n" +
	"\x19REVERSETUNNELPROTOCOL_UDP\x10\x02\x12\x1e\n" +
	"\x1aREVERSETUNNELPROTOCOL_HTTP\x10\x03\x12\x1f\n" +
	"\x1bREVERSETUNNELPROTOCOL_HTTPS\x10\x042e\n" +
	"\x14ReverseTunnelService\x12M\n" +
	"\x0fEstablishTunnel\x12\x19.rtunnel.v1.TunnelMessage\x1a\x19.rtunnel.v1.TunnelMessage\"\x00(\x010\x01B(Z&soft.structx.io/dino/protos/rtunnel/v1b\x06proto3"

var (
	file_pb_rtunnel_v1_rtunnel_service_proto_rawDescOnce sync.Once
	file_pb_rtunnel_v1_rtunnel_service_proto_rawDescData []byte
)

func file_pb_rtunnel_v1_rtunnel_service_proto_rawDescGZIP() []byte {
	file_pb_rtunnel_v1_rtunnel_service_proto_rawDescOnce.Do(func() {
		file_pb_rtunnel_v1_rtunnel_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_rtunnel_v1_rtunnel_service_proto_rawDesc), len(file_pb_rtunnel_v1_rtunnel_service_proto_rawDesc)))
	})
	return file_pb_rtunnel_v1_rtunnel_service_proto_rawDescData
}

var file_pb_rtunnel_v1_rtunnel_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_rtunnel_v1_rtunnel_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_rtunnel_v1_rtunnel_service_proto_goTypes = []any{
	(REVERSETUNNELPROTOCOL)(0), // 0: rtunnel.v1.REVERSETUNNELPROTOCOL
	(*TunnelMessage)(nil),      // 1: rtunnel.v1.TunnelMessage
	(*Route)(nil),              // 2: rtunnel.v1.Route
	(*NewConnection)(nil),      // 3: rtunnel.v1.NewConnection
	(*CloseConnection)(nil),    // 4: rtunnel.v1.CloseConnection
}
var file_pb_rtunnel_v1_rtunnel_service_proto_depIdxs = []int32{
	3, // 0: rtunnel.v1.TunnelMessage.new_connection:type_name -> rtunnel.v1.NewConnection
	4, // 1: rtunnel.v1.TunnelMessage.close_connection:type_name -> rtunnel.v1.CloseConnection
	2, // 2: rtunnel.v1.TunnelMessage.route_updates:type_name -> rtunnel.v1.Route
	0, // 3: rtunnel.v1.NewConnection.protocol:type_name -> rtunnel.v1.REVERSETUNNELPROTOCOL
	1, // 4: rtunnel.v1.ReverseTunnelService.EstablishTunnel:input_type -> rtunnel.v1.TunnelMessage
	1, // 5: rtunnel.v1.ReverseTunnelService.EstablishTunnel:output_type -> rtunnel.v1.TunnelMessage
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pb_rtunnel_v1_rtunnel_service_proto_init() }
func file_pb_rtunnel_v1_rtunnel_service_proto_init() {
	if File_pb_rtunnel_v1_rtunnel_service_proto != nil {
		return
	}
	file_pb_rtunnel_v1_rtunnel_service_proto_msgTypes[0].OneofWrappers = []any{
		(*TunnelMessage_Data)(nil),
		(*TunnelMessage_NewConnection)(nil),
		(*TunnelMessage_CloseConnection)(nil),
		(*TunnelMessage_RouteUpdates)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_rtunnel_v1_rtunnel_service_proto_rawDesc), len(file_pb_rtunnel_v1_rtunnel_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_rtunnel_v1_rtunnel_service_proto_goTypes,
		DependencyIndexes: file_pb_rtunnel_v1_rtunnel_service_proto_depIdxs,
		EnumInfos:         file_pb_rtunnel_v1_rtunnel_service_proto_enumTypes,
		MessageInfos:      file_pb_rtunnel_v1_rtunnel_service_proto_msgTypes,
	}.Build()
	File_pb_rtunnel_v1_rtunnel_service_proto = out.File
	file_pb_rtunnel_v1_rtunnel_service_proto_goTypes = nil
	file_pb_rtunnel_v1_rtunnel_service_proto_depIdxs = nil
}
