// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: pb/rtunnel/v1/rtunnel_service.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReverseTunnelService_EstablishTunnel_FullMethodName = "/rtunnel.v1.ReverseTunnelService/EstablishTunnel"
)

// ReverseTunnelServiceClient is the client API for ReverseTunnelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReverseTunnelServiceClient interface {
	EstablishTunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelMessage, TunnelMessage], error)
}

type reverseTunnelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReverseTunnelServiceClient(cc grpc.ClientConnInterface) ReverseTunnelServiceClient {
	return &reverseTunnelServiceClient{cc}
}

func (c *reverseTunnelServiceClient) EstablishTunnel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TunnelMessage, TunnelMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReverseTunnelService_ServiceDesc.Streams[0], ReverseTunnelService_EstablishTunnel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TunnelMessage, TunnelMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReverseTunnelService_EstablishTunnelClient = grpc.BidiStreamingClient[TunnelMessage, TunnelMessage]

// ReverseTunnelServiceServer is the server API for ReverseTunnelService service.
// All implementations must embed UnimplementedReverseTunnelServiceServer
// for forward compatibility.
type ReverseTunnelServiceServer interface {
	EstablishTunnel(grpc.BidiStreamingServer[TunnelMessage, TunnelMessage]) error
	mustEmbedUnimplementedReverseTunnelServiceServer()
}

// UnimplementedReverseTunnelServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReverseTunnelServiceServer struct{}

func (UnimplementedReverseTunnelServiceServer) EstablishTunnel(grpc.BidiStreamingServer[TunnelMessage, TunnelMessage]) error {
	return status.Error(codes.Unimplemented, "method EstablishTunnel not implemented")
}
func (UnimplementedReverseTunnelServiceServer) mustEmbedUnimplementedReverseTunnelServiceServer() {}
func (UnimplementedReverseTunnelServiceServer) testEmbeddedByValue()                              {}

// UnsafeReverseTunnelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReverseTunnelServiceServer will
// result in compilation errors.
type UnsafeReverseTunnelServiceServer interface {
	mustEmbedUnimplementedReverseTunnelServiceServer()
}

func RegisterReverseTunnelServiceServer(s grpc.ServiceRegistrar, srv ReverseTunnelServiceServer) {
	// If the following call panics, it indicates UnimplementedReverseTunnelServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReverseTunnelService_ServiceDesc, srv)
}

func _ReverseTunnelService_EstablishTunnel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReverseTunnelServiceServer).EstablishTunnel(&grpc.GenericServerStream[TunnelMessage, TunnelMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReverseTunnelService_EstablishTunnelServer = grpc.BidiStreamingServer[TunnelMessage, TunnelMessage]

// ReverseTunnelService_ServiceDesc is the grpc.ServiceDesc for ReverseTunnelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReverseTunnelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rtunnel.v1.ReverseTunnelService",
	HandlerType: (*ReverseTunnelServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EstablishTunnel",
			Handler:       _ReverseTunnelService_EstablishTunnel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pb/rtunnel/v1/rtunnel_service.proto",
}
